# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - npm run dev
    sources:
      - src/**/*.ts
      - src/**/*.js
      - src/**/*.html
      - src/**/*.css
      - src/**/*.svelte
      - wxt-env.d.ts
      - wxt.config.ts
    watch: true
    silent: true
